# Generated by Django 3.2 on 2022-04-22 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_beds_no', models.IntegerField(blank=True, null=True)),
                ('total_staff', models.IntegerField(blank=True, null=True)),
                ('total_biomedical_equipments', models.IntegerField(blank=True, null=True)),
                ('total_patients_admitted', models.IntegerField(blank=True, null=True)),
                ('equipment_emergency_for_patients', models.CharField(blank=True, choices=[('Never', 'Never'), ('Rarely (1-3 patients/month', 'Rarely (1-3 patients/month'), ('Many times (4-9 patients/month', 'Many times (4-9 patients/month'), ('Frequently (410 patients/month', 'Frequently (410 patients/month'), ('I do not know', 'I do not know')], max_length=255, null=True)),
                ('must_used_equipments', models.CharField(blank=True, max_length=255, null=True)),
                ('yearly_expenditure_spent_for_equipments', models.CharField(blank=True, choices=[('Less than 1 lakh', 'Less than 1 lakh'), ('1-50 lakh', '1-50 lakh'), ('50 lakh - 1 crore', '50 lakh - 1 crore'), ('more than 1 crore', 'more than 1 crore')], max_length=255, null=True)),
                ('calibrate_biomedical_equipment', models.CharField(blank=True, choices=[('Twice in a year', 'Twice in an year'), ('Once a year', 'Once a year'), ('After problem arises', 'After problem arises'), ('other', 'other')], max_length=255, null=True)),
                ('biomedical_calibrate_from_others', models.CharField(blank=True, max_length=400, null=True)),
                ('are_hospital_repaire_equipments', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'No')], max_length=255, null=True)),
                ('aware_about_calibration_of_biomedical_equipment', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'No')], max_length=255, null=True)),
                ('repair_and_maintenance', models.CharField(blank=True, choices=[('Twice in a year', 'Twice in an year'), ('Once a year', 'Once a year'), ('After problem arises', 'After problem arises'), ('other', 'other')], max_length=255, null=True)),
                ('repaired_by', models.CharField(blank=True, choices=[('self', 'self'), ('from others', 'from others')], max_length=255, null=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.hospital')),
            ],
        ),
    ]
