# Generated by Django 3.2 on 2022-04-26 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_hospitalinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalinfo',
            old_name='are_hospital_repaire_equipments',
            new_name='are_hospital_repair_equipments',
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
