# Generated by Django 3.2 on 2022-04-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20220426_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('ICU Machine', 'ICU Machine'), ('Ventilator Machine', 'Ventilator Machine'), ('Patient Monitor', 'Patient Monitor'), ('Infusion Pump', 'Infusion Pump'), ('Suction Pump', 'Suction Pump'), ('X-ray Machine', 'X-ray Machine'), ('Arterial Blood Gas (ABG) Machine', 'Arterial Blood Gas (ABG) Machine'), ('Defibrillator', 'Defibrillator'), ('BiPap Machine (bilevel positive airway pressure)', 'BiPap Machine (bilevel positive airway pressure)'), ('CPAP Machine (Continuous positive airway pressure', 'CPAP Machine (Continuous positive airway pressure'), ('High flow Nasal Cannula', 'High flow Nasal Cannula'), ('ECG Machine', 'ECG Machine'), ('Oxygen Concentrator', 'Oxygen Concentrator'), ('Autoclave Machine', 'Autoclave Machine'), ('BSC Level', 'BSC Level'), ('Automated Extraction', 'Automated Extraction'), ('PCR Machine', 'PCR Machine')], max_length=255, null=True)),
                ('equipments_before_covid', models.CharField(blank=True, max_length=255, null=True)),
                ('equipments_after_covid', models.CharField(blank=True, max_length=255, null=True)),
                ('operational', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Biomedical Engineer', 'Biomedical Engineer'), ('Biomedical Technician', 'Biomedical Technician'), ('Health Assistant', 'Health Assistant'), ('Lab Technician', 'Lab Technician'), ('Radiographer', 'Radiographer'), ('Other Paramedics', 'Other Paramedics')], max_length=255, null=True)),
                ('staff_type', models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Development Committee', 'Development Committee')], max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.CharField(blank=True, choices=[('ICU', 'ICU'), ('HDU', 'DHU'), ('High Flow Nasal Cannula', 'High Flow Nasal Cannula'), ('Isolation', 'Isolation'), ('Oxygen Supply', 'Oxygen Supply')], max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.hospital')),
            ],
        ),
    ]
