# Generated by Django 3.2 on 2022-05-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20220427_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalinfo',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='equipmentinfo',
            name='hospital',
        ),
        migrations.AddField(
            model_name='hospital',
            name='BiomedicalEngineerDevelopmentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='BiomedicalEngineerPermanentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='BiomedicalEngineerTemperoraystaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='BiomedicalTechnicianDevelopmentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='BiomedicalTechnicianPermanentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='BiomedicalTechnicianTemperoraystaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='DoctorDevelopmentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='DoctorPermanentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='DoctorTemperoraystaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='EquipmentInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.equipmentinfo'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HDUbeds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HDUpatientsadmitted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HDUpatientsdeaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HDUpatientsdischarged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HFNCbeds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HFNCpatientsadmitted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HFNCpatientsdeaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HFNCpatientsdischarged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HealthAssistanDevelopmentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HealthAssistanPermanentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='HealthAssistanTemperoraystaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ICUbeds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ICUpatientsadmitted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ICUpatientsdeaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ICUpatientsdischarged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Isolationbeds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Isolationpatientsadmitted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Isolationpatientsdeaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Isolationpatientsdischarged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='LabTechnicianDevelopmentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='LabTechnicianPermanentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='LabTechnicianTemperoraystaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='NurseDevelopmentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='NursePermanentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='NurseTemperoraystaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='OtherParamedicsDevelopmentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='OtherParamedicsPermanentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='OtherParamedicsTemperoraystaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Oxygensuppliedbeds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Oxygensuppliedpatientsadmitted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Oxygensuppliedpatientsdeaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Oxygensuppliedpatientsdischarged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='PharmacistDevelopmentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='PharmacistPermanentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='PharmacistTemperoraystaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='RadiographerDevelopmentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='RadiographerPermanentstaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='RadiographerTemperoraystaff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Ventilatorpatientsadmitted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Ventilatorpatientsdeaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Ventilatorpatientsdischarged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='company_name_np',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='eqiupment_status',
            field=models.CharField(blank=True, choices=[('Operational', 'Operational'), ('Not Operational', 'Not Operational'), ('In Maintenance', 'In Maintenance')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='equipment_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='equipment_type_np',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='model_number_np',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='remarks_np',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='suppliers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='suppliers_np',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='unit_np',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
        migrations.DeleteModel(
            name='HospitalInfo',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
