# Generated by Django 3.2 on 2022-06-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20220506_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='company_name',
            new_name='must_used_equipments',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='company_name_np',
            new_name='operational',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='BiomedicalEngineerDevelopmentstaff',
            new_name='total_biomedical_equipments',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='BiomedicalEngineerPermanentstaff',
            new_name='total_patients_admitted',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='eqiupment_status',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='BiomedicalEngineerTemperoraystaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='BiomedicalTechnicianDevelopmentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='BiomedicalTechnicianPermanentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='BiomedicalTechnicianTemperoraystaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='DoctorDevelopmentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='DoctorPermanentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='DoctorTemperoraystaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='EquipmentInfo',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HDUbeds',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HDUpatientsadmitted',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HDUpatientsdeaths',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HDUpatientsdischarged',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HFNCbeds',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HFNCpatientsadmitted',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HFNCpatientsdeaths',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HFNCpatientsdischarged',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HealthAssistanDevelopmentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HealthAssistanPermanentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HealthAssistanTemperoraystaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='ICUbeds',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='ICUpatientsadmitted',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='ICUpatientsdeaths',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='ICUpatientsdischarged',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Isolationbeds',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Isolationpatientsadmitted',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Isolationpatientsdeaths',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Isolationpatientsdischarged',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='LabTechnicianDevelopmentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='LabTechnicianPermanentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='LabTechnicianTemperoraystaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='NurseDevelopmentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='NursePermanentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='NurseTemperoraystaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='OtherParamedicsDevelopmentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='OtherParamedicsPermanentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='OtherParamedicsTemperoraystaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Oxygensuppliedbeds',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Oxygensuppliedpatientsadmitted',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Oxygensuppliedpatientsdeaths',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Oxygensuppliedpatientsdischarged',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='PharmacistDevelopmentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='PharmacistPermanentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='PharmacistTemperoraystaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='RadiographerDevelopmentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='RadiographerPermanentstaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='RadiographerTemperoraystaff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Ventilatorpatientsadmitted',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Ventilatorpatientsdeaths',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Ventilatorpatientsdischarged',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='eqiupment_status',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='equipment_type_np',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='model_number_np',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='remarks_np',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='suppliers',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='suppliers_np',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='unit_np',
        ),
        migrations.AddField(
            model_name='equipment',
            name='in_maintenance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='not_operational',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='operational',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='total_equipments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='are_hospital_repair_equipments',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='aware_about_calibration_of_biomedical_equipment',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='biomedical_calibrate_from_others',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='biomedical_engineer_development_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='biomedical_engineer_permanent_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='biomedical_engineer_temperoray_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='biomedical_technician_development_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='biomedical_technician_permanent_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='biomedical_technician_temperoray_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='calibrate_biomedical_equipment',
            field=models.CharField(blank=True, choices=[('Twice in a year', 'Twice in an year'), ('Once a year', 'Once a year'), ('After problem arises', 'After problem arises'), ('other', 'other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctor_development_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctor_permanents_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctor_temperoray_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='equipment_emergency_for_patients',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Rarely (1-3 patients/month', 'Rarely (1-3 patients/month'), ('Many times (4-9 patients/month', 'Many times (4-9 patients/month'), ('Frequently (410 patients/month', 'Frequently (410 patients/month'), ('I do not know', 'I do not know')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='equipments_after_covid',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='equipments_before_covid',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='equipments_name',
            field=models.CharField(blank=True, choices=[('ICU Machine', 'ICU Machine'), ('Ventilator Machine', 'Ventilator Machine'), ('Patient Monitor', 'Patient Monitor'), ('Infusion Pump', 'Infusion Pump'), ('Suction Pump', 'Suction Pump'), ('X-ray Machine', 'X-ray Machine'), ('Arterial Blood Gas (ABG) Machine', 'Arterial Blood Gas (ABG) Machine'), ('Defibrillator', 'Defibrillator'), ('BiPap Machine (bilevel positive airway pressure)', 'BiPap Machine (bilevel positive airway pressure)'), ('CPAP Machine (Continuous positive airway pressure', 'CPAP Machine (Continuous positive airway pressure'), ('High flow Nasal Cannula', 'High flow Nasal Cannula'), ('ECG Machine', 'ECG Machine'), ('Oxygen Concentrator', 'Oxygen Concentrator'), ('Autoclave Machine', 'Autoclave Machine'), ('BSC Level', 'BSC Level'), ('Automated Extraction', 'Automated Extraction'), ('PCR Machine', 'PCR Machine')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hdu_beds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hdu_patients_admitted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hdu_patients_deaths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hdu_patients_discharged',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='health_assistant_development_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='health_assistant_permanent_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='health_assistant_temperoray_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hfnc_beds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hfnc_patients_admitted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hfnc_patients_deaths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hfnc_patients_discharged',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='icu_beds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='icu_patients_admitted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='icu_patients_deaths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='icu_patients_discharged',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='isolation_beds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='isolation_patients_admitted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='isolation_patients_deaths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='isolation_patients_discharged',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lab_technician_development_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lab_technician_permanent_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lab_technician_temperoray_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nurse_development_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nurse_permanent_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nurse_temperoray_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='other_paramedics_development_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='other_paramedics_permanent_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='other_paramedics_temperoray_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='oxygen_supplied_beds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='oxygen_supplied_patients_admitted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='oxygen_supplied_patients_deaths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='oxygen_supplied_patients_discharged',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pharmacist_development_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pharmacist_permanent_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pharmacist_temperoray_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='radio_grapher_development_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='radio_grapher_permanent_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='radio_grapher_temperoray_staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='repair_and_maintenance',
            field=models.CharField(blank=True, choices=[('Twice in a year', 'Twice in an year'), ('Once a year', 'Once a year'), ('After problem arises', 'After problem arises'), ('other', 'other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='repaired_by',
            field=models.CharField(blank=True, choices=[('self', 'self'), ('from others', 'from others')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ventilator_patients_admitted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ventilator_patients_deaths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ventilator_patients_discharged',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='yearly_expenditure_spent_for_equipments',
            field=models.CharField(blank=True, choices=[('Less than 1 lakh', 'Less than 1 lakh'), ('1-50 lakh', '1-50 lakh'), ('50 lakh - 1 crore', '50 lakh - 1 crore'), ('more than 1 crore', 'more than 1 crore')], max_length=255, null=True),
        ),
    ]
