# Generated by Django 3.2 on 2022-06-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skills',
            new_name='skill',
        ),
    ]
