# Generated by Django 3.2 on 2022-07-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_trainings'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='associated_organization_or_clinic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='certification_from_mot',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='ege_group',
            field=models.CharField(blank=True, choices=[('Below 19', 'Below 19'), ('20-29', '20-29'), ('30-39', '30-39'), ('40-49', '40-49'), ('50-59', '50-59'), ('Above 60', 'Above 60')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='ethnic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
