# Generated by Django 3.2 on 2022-08-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_auto_20220706_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='lalitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='trainings',
            name='logitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
