# Generated by Django 3.2 on 2022-08-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_auto_20220803_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='longitude',
            new_name='logitude',
        ),
    ]
