# Generated by Django 3.2 on 2022-08-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_rename_longitude_trainer_logitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='about.district'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='about.municipality'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='about.province'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='about.ward'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
